#!/usr/bin/env python3
"""End-to-end assertions for opt-in single-file and project source maps."""

from __future__ import annotations

import json
import os
import subprocess
import tempfile
from pathlib import Path


def fnv1a64(data: bytes) -> str:
    value = 0xCBF29CE484222325
    for byte in data:
        value = ((value ^ byte) * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return f"{value:016x}"


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    translator = Path(
        os.environ.get("ELISA_TRANSLATOR_BIN", root / "build" / "elisa-c-transpiler")
    ).resolve()
    if not translator.is_file():
        raise SystemExit(f"translator executable not found: {translator}")
    with tempfile.TemporaryDirectory(prefix='source map " ') as temporary:
        directory = Path(temporary)
        header = directory / "macro origin.h"
        source = directory / 'main " source.c'
        output_map = directory / "translation.map.json"
        header.write_text("#define RETURN_VALUE(value) return (value)\n")
        source.write_text(
            '#include "macro origin.h"\n'
            "int answer(void) { RETURN_VALUE(42); }\n"
        )

        command = [str(translator), "--source-map-json", str(output_map), str(source)]
        first = subprocess.run(command, cwd=root, capture_output=True, check=False)
        assert first.returncode == 0, first.stderr.decode(errors="replace")
        assert first.stdout.startswith(b"# Generated by the Elisa C translator.")
        first_map = output_map.read_bytes()
        parsed = json.loads(first_map)
        assert parsed["schema_version"] == 3
        assert parsed["offset_unit"] == "byte"
        assert parsed["offset_convention"] == "zero-based-half-open"
        assert parsed["hash_algorithm"] == "fnv1a64"
        assert parsed["mappings"]

        source_records = {record["path"]: record for record in parsed["sources"]}
        assert source_records
        translation_unit_paths = {
            record["path"]
            for record in source_records.values()
            if record["canonical_path"] == str(source.resolve())
        }
        assert any(
            Path(mapping["spelling"]["path"]).name == header.name
            for mapping in parsed["mappings"]
        ), "macro spelling should point back to the defining header"
        assert any(
            Path(origin["included_from"]).name == source.name
            for mapping in parsed["mappings"]
            for origin in (mapping["source"], mapping["spelling"], mapping["expansion"])
            if origin["included_from"]
        ), "source origins should retain Clang's immediate include edge"
        expected_contents = {
            str(source.resolve()): source.read_bytes(),
            str(header.resolve()): header.read_bytes(),
        }
        for record in source_records.values():
            contents = expected_contents.get(record["canonical_path"])
            assert contents is not None, record
            assert record["content_hash"] == fnv1a64(contents)

        for mapping in parsed["mappings"]:
            assert 0 <= mapping["generated_start"] <= mapping["generated_end"] <= len(first.stdout)
            assert set(mapping) == {
                "generated_start", "generated_end", "translation_unit", "source", "spelling", "expansion", "synthesized_reason"
            }
            assert mapping["translation_unit"] == str(source.resolve())
            for origin in (mapping["source"], mapping["spelling"], mapping["expansion"]):
                assert set(origin) == {
                    "path", "included_from", "content_hash", "included_from_content_hash",
                    "start_offset", "end_offset",
                }
                source_record = source_records.get(origin["path"])
                include_record = source_records.get(origin["included_from"])
                assert origin["content_hash"] == (
                    source_record["content_hash"] if source_record is not None else None
                )
                assert origin["included_from_content_hash"] == (
                    include_record["content_hash"] if include_record is not None else None
                )
                if origin["path"] in source_records:
                    source_bytes = expected_contents[source_records[origin["path"]]["canonical_path"]]
                    start, end = origin["start_offset"], origin["end_offset"]
                    assert start >= -1 and end >= -1
                    assert start < 0 or end < 0 or 0 <= start <= end <= len(source_bytes)
        assert any(
            mapping["expansion"]["path"] in translation_unit_paths
            and b"42" in first.stdout[mapping["generated_start"]:mapping["generated_end"]]
            for mapping in parsed["mappings"]
        ), "the expansion origin must map to generated bytes for the macro's return value"

        synthetic_source = root / "testdata" / "fixtures" / "loop_condition_effects.c"
        synthetic_map_path = directory / "synthesized.map.json"
        synthetic = subprocess.run(
            [str(translator), "--source-map-json", str(synthetic_map_path), str(synthetic_source)],
            cwd=root,
            capture_output=True,
            check=False,
        )
        assert synthetic.returncode == 0, synthetic.stderr.decode(errors="replace")
        synthetic_document = json.loads(synthetic_map_path.read_bytes())
        synthesized_mappings = [
            mapping
            for mapping in synthetic_document["mappings"]
            if mapping["synthesized_reason"]
        ]
        assert synthesized_mappings, "lowered control-flow statements should explain synthesized spans"
        assert all(
            mapping["synthesized_reason"] == "synthesized while lowering parent Clang statement"
            and 0 <= mapping["generated_start"] <= mapping["generated_end"] <= len(synthetic.stdout)
            for mapping in synthesized_mappings
        )

        macro_only_source = directory / "macro-only.c"
        macro_only_source.write_text("#define UNUSED_VALUE 17\n")
        macro_only_map = directory / "macro-only.map.json"
        macro_only = subprocess.run(
            [str(translator), "--source-map-json", str(macro_only_map), str(macro_only_source)],
            cwd=root,
            capture_output=True,
            check=False,
        )
        assert macro_only.returncode == 0, macro_only.stderr.decode(errors="replace")
        macro_only_document = json.loads(macro_only_map.read_bytes())
        assert macro_only_document["mappings"] == [], "macro-only translation should have no emitted-origin mappings"
        root_source_record = next(
            (
                record
                for record in macro_only_document["sources"]
                if record["canonical_path"] == str(macro_only_source.resolve())
            ),
            None,
        )
        assert root_source_record is not None, "source maps must hash the translation unit even with no emitted origins"
        assert root_source_record["content_hash"] == fnv1a64(macro_only_source.read_bytes())

        second = subprocess.run(command, cwd=root, capture_output=True, check=False)
        assert second.returncode == 0, second.stderr.decode(errors="replace")
        assert output_map.read_bytes() == first_map, "source-map JSON must be deterministic"
        assert second.stdout == first.stdout
        assert not list(directory.glob("translation.map.json.elisa-source-map-tmp-*"))

        missing_path = subprocess.run(
            [str(translator), "--source-map-json"],
            cwd=root,
            capture_output=True,
            check=False,
        )
        assert missing_path.returncode == 2
        assert b"requires an output path" in missing_path.stderr

        original_source = source.read_bytes()
        collision = subprocess.run(
            [str(translator), "--source-map-json", str(source), str(source)],
            cwd=root,
            capture_output=True,
            check=False,
        )
        assert collision.returncode != 0
        assert not collision.stdout
        assert b"refusing to overwrite" in collision.stderr
        assert source.read_bytes() == original_source

        project_dir = directory / "project"
        project_dir.mkdir()
        source_alias = project_dir / "source-alias.map.json"
        source_alias.symlink_to(source.resolve())
        project_source_collision = subprocess.run(
            [
                str(translator),
                "--output-dir", str(project_dir),
                "--source-map-json", str(source_alias),
                str(source),
            ],
            cwd=root,
            capture_output=True,
            check=False,
        )
        assert project_source_collision.returncode == 2
        assert not project_source_collision.stdout
        assert b"resolves to an input source" in project_source_collision.stderr
        assert source_alias.is_symlink()
        assert source.read_bytes() == original_source
        source_alias.unlink()

        project_map = project_dir / "project.source-map.json"
        second_source = directory / "second.c"
        second_source.write_text(
            '#include "macro origin.h"\n'
            "int second_answer(void) { RETURN_VALUE(84); }\n"
        )
        project_macro_only = directory / "project-macro-only.c"
        project_macro_only.write_text("#define PROJECT_UNUSED_VALUE 23\n")
        project_command = [
            str(translator),
            "--output-dir", str(project_dir),
            "--source-map-json", str(project_map),
            str(source),
            str(second_source),
            str(project_macro_only),
        ]
        project = subprocess.run(
            project_command,
            cwd=root,
            capture_output=True,
            check=False,
        )
        assert project.returncode == 0, project.stderr.decode(errors="replace")
        assert not project.stdout
        project_json = json.loads(project_map.read_bytes())
        assert project_json["schema_version"] == 1
        assert len(project_json["units"]) == 3
        units_by_source = {
            unit["translation_source"]: unit for unit in project_json["units"]
        }
        assert set(units_by_source) == {
            str(source.resolve()),
            str(second_source.resolve()),
            str(project_macro_only.resolve()),
        }
        assert units_by_source[str(source.resolve())]["map"]["mappings"]
        assert units_by_source[str(second_source.resolve())]["map"]["mappings"]
        for source_path in (str(source.resolve()), str(second_source.resolve())):
            unit_map = units_by_source[source_path]["map"]
            assert unit_map["schema_version"] == 3
            unit_records = {record["path"]: record for record in unit_map["sources"]}
            for mapping in unit_map["mappings"]:
                for origin in (mapping["source"], mapping["spelling"], mapping["expansion"]):
                    file_record = unit_records.get(origin["path"])
                    include_record = unit_records.get(origin["included_from"])
                    assert origin["content_hash"] == (
                        file_record["content_hash"] if file_record is not None else None
                    )
                    assert origin["included_from_content_hash"] == (
                        include_record["content_hash"] if include_record is not None else None
                    )
        assert all(
            mapping["translation_unit"] == source_path
            for source_path in (str(source.resolve()), str(second_source.resolve()))
            for mapping in units_by_source[source_path]["map"]["mappings"]
        )
        project_macro_record = next(
            (
                record
                for record in units_by_source[str(project_macro_only.resolve())]["map"]["sources"]
                if record["canonical_path"] == str(project_macro_only.resolve())
            ),
            None,
        )
        assert project_macro_record is not None, "project maps must hash origin-free translation units"
        assert project_macro_record["content_hash"] == fnv1a64(project_macro_only.read_bytes())
        for source_path in (str(source.resolve()), str(second_source.resolve())):
            assert any(
                Path(record["canonical_path"]).name == header.name
                for record in units_by_source[source_path]["map"]["sources"]
            ), "each project unit should retain its macro header origin"
        header_hashes = [
            next(
                record["content_hash"]
                for record in units_by_source[source_path]["map"]["sources"]
                if record["canonical_path"] == str(header.resolve())
            )
            for source_path in (str(source.resolve()), str(second_source.resolve()))
        ]
        assert header_hashes == [fnv1a64(header.read_bytes())] * 2
        first_project_map = project_map.read_bytes()
        repeated_project = subprocess.run(
            project_command,
            cwd=root,
            capture_output=True,
            check=False,
        )
        assert repeated_project.returncode == 0, repeated_project.stderr.decode(errors="replace")
        assert project_map.read_bytes() == first_project_map, "project source-map JSON must be deterministic"

        old_project_map = project_map.read_bytes()
        old_manifest = (project_dir / "elisa_project.elisa").read_bytes()
        old_modules = {path.name: path.read_bytes() for path in project_dir.glob("*.elisa") if path.name != "elisa_project.elisa"}

        assert old_modules, "project translation should publish at least one module"
        generated_module = project_dir / sorted(old_modules)[0]
        for colliding_target in (generated_module, project_dir / "elisa_project.elisa"):
            symlinked_map_path = project_dir / f"map-alias-{colliding_target.name}.json"
            symlinked_map_path.symlink_to(colliding_target)
            for colliding_map_path in (colliding_target, symlinked_map_path):
                project_output_collision = subprocess.run(
                    [
                        str(translator),
                        "--output-dir", str(project_dir),
                        "--source-map-json", str(colliding_map_path),
                        str(source),
                        str(second_source),
                        str(project_macro_only),
                    ],
                    cwd=root,
                    capture_output=True,
                    check=False,
                )
                assert project_output_collision.returncode == 2
                assert not project_output_collision.stdout
                assert b"collides" in project_output_collision.stderr
            assert symlinked_map_path.is_symlink(), "collision refusal must preserve the caller's symlink"
            symlinked_map_path.unlink()
        assert project_map.read_bytes() == old_project_map
        assert (project_dir / "elisa_project.elisa").read_bytes() == old_manifest
        assert {path.name: path.read_bytes() for path in project_dir.glob("*.elisa") if path.name != "elisa_project.elisa"} == old_modules

        project_good = directory / "a_project_good.c"
        project_bad = directory / "z_project_bad.c"
        project_good.write_text("int project_value(void) { return 7; }\n")
        project_bad.write_bytes((root / "testdata" / "fixtures" / "conditional_comma_unsupported.c").read_bytes())
        failed = subprocess.run(
            [
                str(translator),
                "--output-dir", str(project_dir),
                "--source-map-json", str(project_map),
                str(project_good),
                str(project_bad),
            ],
            cwd=root,
            capture_output=True,
            check=False,
        )
        assert failed.returncode != 0
        assert not failed.stdout
        assert project_map.read_bytes() == old_project_map, "failed projects must preserve the prior map"
        assert (project_dir / "elisa_project.elisa").read_bytes() == old_manifest
        assert {path.name: path.read_bytes() for path in project_dir.glob("*.elisa") if path.name != "elisa_project.elisa"} == old_modules
        assert not list(project_dir.glob("*.elisa-transpiler-tmp-*")), "failed projects must remove transaction staging files"

    print("source-map CLI checks passed")


if __name__ == "__main__":
    main()
